// <auto-generated />
using System;
using BackEndAeroQA.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndAeroQA.Infrastructure.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEndAeroQA.Domain.Entity.Passageiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passageiros");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb763957-94ac-4cc8-9b0d-58d1e87056b3"),
                            Cpf = "CPF1",
                            DataDeNascimento = new DateTime(1990, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(860),
                            Email = "passageiro1@exemplo.com",
                            Name = "Passageiro 1"
                        },
                        new
                        {
                            Id = new Guid("f519b487-f7fb-4a73-8850-8b7e9a05e11c"),
                            Cpf = "CPF2",
                            DataDeNascimento = new DateTime(1979, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(893),
                            Email = "passageiro2@exemplo.com",
                            Name = "Passageiro 2"
                        },
                        new
                        {
                            Id = new Guid("c4d4f186-f91b-494a-b6f5-dbe4889a1f06"),
                            Cpf = "CPF3",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(902),
                            Email = "passageiro3@exemplo.com",
                            Name = "Passageiro 3"
                        },
                        new
                        {
                            Id = new Guid("40436bef-87f7-4061-b3da-aa8ce621ac2b"),
                            Cpf = "CPF4",
                            DataDeNascimento = new DateTime(1975, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(915),
                            Email = "passageiro4@exemplo.com",
                            Name = "Passageiro 4"
                        },
                        new
                        {
                            Id = new Guid("aa357910-d696-47b3-8f40-c5f963409fab"),
                            Cpf = "CPF5",
                            DataDeNascimento = new DateTime(1994, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(921),
                            Email = "passageiro5@exemplo.com",
                            Name = "Passageiro 5"
                        },
                        new
                        {
                            Id = new Guid("7bdef3c0-8dec-4f51-847a-e751b1f73c44"),
                            Cpf = "CPF6",
                            DataDeNascimento = new DateTime(1981, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(928),
                            Email = "passageiro6@exemplo.com",
                            Name = "Passageiro 6"
                        },
                        new
                        {
                            Id = new Guid("41ffb3fd-a6c6-4595-8717-e4f1b46e80ba"),
                            Cpf = "CPF7",
                            DataDeNascimento = new DateTime(1994, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(935),
                            Email = "passageiro7@exemplo.com",
                            Name = "Passageiro 7"
                        },
                        new
                        {
                            Id = new Guid("bcfec78f-023e-44be-aeda-b3bbc8adb764"),
                            Cpf = "CPF8",
                            DataDeNascimento = new DateTime(1992, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(945),
                            Email = "passageiro8@exemplo.com",
                            Name = "Passageiro 8"
                        },
                        new
                        {
                            Id = new Guid("f87163cf-9561-414b-9e19-360c23fb581f"),
                            Cpf = "CPF9",
                            DataDeNascimento = new DateTime(1985, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(953),
                            Email = "passageiro9@exemplo.com",
                            Name = "Passageiro 9"
                        },
                        new
                        {
                            Id = new Guid("c5b7a6f9-8552-40cb-89a4-eb37e57cea97"),
                            Cpf = "CPF10",
                            DataDeNascimento = new DateTime(1993, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(964),
                            Email = "passageiro10@exemplo.com",
                            Name = "Passageiro 10"
                        },
                        new
                        {
                            Id = new Guid("4383fbf0-ae17-4c57-befa-4cf4a2079f1c"),
                            Cpf = "CPF11",
                            DataDeNascimento = new DateTime(1977, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(971),
                            Email = "passageiro11@exemplo.com",
                            Name = "Passageiro 11"
                        },
                        new
                        {
                            Id = new Guid("1fb16bcf-dbd2-4a68-8429-7d35b77d4a58"),
                            Cpf = "CPF12",
                            DataDeNascimento = new DateTime(1984, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(982),
                            Email = "passageiro12@exemplo.com",
                            Name = "Passageiro 12"
                        },
                        new
                        {
                            Id = new Guid("0120735f-7cf1-4cc1-a204-b8b7f0db9b22"),
                            Cpf = "CPF13",
                            DataDeNascimento = new DateTime(1990, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(990),
                            Email = "passageiro13@exemplo.com",
                            Name = "Passageiro 13"
                        },
                        new
                        {
                            Id = new Guid("df4781b1-f3c0-451b-8dac-3a0f59e93d54"),
                            Cpf = "CPF14",
                            DataDeNascimento = new DateTime(1996, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(998),
                            Email = "passageiro14@exemplo.com",
                            Name = "Passageiro 14"
                        },
                        new
                        {
                            Id = new Guid("938b5420-96e7-48cb-831c-cf4f16c9646a"),
                            Cpf = "CPF15",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1007),
                            Email = "passageiro15@exemplo.com",
                            Name = "Passageiro 15"
                        },
                        new
                        {
                            Id = new Guid("2c283782-6a9b-439a-a7df-985adebda5aa"),
                            Cpf = "CPF16",
                            DataDeNascimento = new DateTime(1979, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1018),
                            Email = "passageiro16@exemplo.com",
                            Name = "Passageiro 16"
                        },
                        new
                        {
                            Id = new Guid("8bf3d8c6-95b2-4b29-91d8-da85b7d68d86"),
                            Cpf = "CPF17",
                            DataDeNascimento = new DateTime(1996, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1026),
                            Email = "passageiro17@exemplo.com",
                            Name = "Passageiro 17"
                        },
                        new
                        {
                            Id = new Guid("169f7bc7-2787-49fb-9741-efa5199761a9"),
                            Cpf = "CPF18",
                            DataDeNascimento = new DateTime(1967, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1033),
                            Email = "passageiro18@exemplo.com",
                            Name = "Passageiro 18"
                        },
                        new
                        {
                            Id = new Guid("4981053b-af5d-474d-9164-02dc7611236e"),
                            Cpf = "CPF19",
                            DataDeNascimento = new DateTime(1968, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1040),
                            Email = "passageiro19@exemplo.com",
                            Name = "Passageiro 19"
                        },
                        new
                        {
                            Id = new Guid("fba00750-ee6f-4ff1-b15c-9bf34ab7a5d8"),
                            Cpf = "CPF20",
                            DataDeNascimento = new DateTime(1986, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1050),
                            Email = "passageiro20@exemplo.com",
                            Name = "Passageiro 20"
                        },
                        new
                        {
                            Id = new Guid("065e0ad7-e565-4dce-85c6-94d1e57c7aa1"),
                            Cpf = "CPF21",
                            DataDeNascimento = new DateTime(2006, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1057),
                            Email = "passageiro21@exemplo.com",
                            Name = "Passageiro 21"
                        },
                        new
                        {
                            Id = new Guid("e4b90979-0702-4847-8bef-8a97f2d9a2f6"),
                            Cpf = "CPF22",
                            DataDeNascimento = new DateTime(1980, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1122),
                            Email = "passageiro22@exemplo.com",
                            Name = "Passageiro 22"
                        },
                        new
                        {
                            Id = new Guid("558e993b-61d6-44e7-9dc3-fe869e810925"),
                            Cpf = "CPF23",
                            DataDeNascimento = new DateTime(1997, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1129),
                            Email = "passageiro23@exemplo.com",
                            Name = "Passageiro 23"
                        },
                        new
                        {
                            Id = new Guid("bae570c6-87dc-4444-906d-6c908120a531"),
                            Cpf = "CPF24",
                            DataDeNascimento = new DateTime(1991, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1140),
                            Email = "passageiro24@exemplo.com",
                            Name = "Passageiro 24"
                        },
                        new
                        {
                            Id = new Guid("183fbd4c-5e80-4abf-a36e-fad7dbfc18be"),
                            Cpf = "CPF25",
                            DataDeNascimento = new DateTime(1995, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1147),
                            Email = "passageiro25@exemplo.com",
                            Name = "Passageiro 25"
                        },
                        new
                        {
                            Id = new Guid("3347652a-32e7-4ac0-9319-0a28f39da501"),
                            Cpf = "CPF26",
                            DataDeNascimento = new DateTime(1975, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1153),
                            Email = "passageiro26@exemplo.com",
                            Name = "Passageiro 26"
                        },
                        new
                        {
                            Id = new Guid("50e6ea17-0c9c-4102-8f36-acf0d116775f"),
                            Cpf = "CPF27",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1160),
                            Email = "passageiro27@exemplo.com",
                            Name = "Passageiro 27"
                        },
                        new
                        {
                            Id = new Guid("8f362b45-63ca-4618-bc9e-c6a58232848e"),
                            Cpf = "CPF28",
                            DataDeNascimento = new DateTime(1996, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1172),
                            Email = "passageiro28@exemplo.com",
                            Name = "Passageiro 28"
                        },
                        new
                        {
                            Id = new Guid("be51acf0-018a-4b58-9aca-919490185460"),
                            Cpf = "CPF29",
                            DataDeNascimento = new DateTime(1976, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1181),
                            Email = "passageiro29@exemplo.com",
                            Name = "Passageiro 29"
                        },
                        new
                        {
                            Id = new Guid("0155e81c-f2bc-422d-adb9-13cdd2ce855a"),
                            Cpf = "CPF30",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1189),
                            Email = "passageiro30@exemplo.com",
                            Name = "Passageiro 30"
                        },
                        new
                        {
                            Id = new Guid("105ba57b-20ae-497f-a0d1-8b659540ea0c"),
                            Cpf = "CPF31",
                            DataDeNascimento = new DateTime(1999, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1196),
                            Email = "passageiro31@exemplo.com",
                            Name = "Passageiro 31"
                        },
                        new
                        {
                            Id = new Guid("ef34fa59-c9fc-4cb7-b720-fb4e634ed148"),
                            Cpf = "CPF32",
                            DataDeNascimento = new DateTime(2002, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1207),
                            Email = "passageiro32@exemplo.com",
                            Name = "Passageiro 32"
                        },
                        new
                        {
                            Id = new Guid("9af3a1a1-e90c-4b67-a73e-41bea1052c5e"),
                            Cpf = "CPF33",
                            DataDeNascimento = new DateTime(2001, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1215),
                            Email = "passageiro33@exemplo.com",
                            Name = "Passageiro 33"
                        },
                        new
                        {
                            Id = new Guid("c6f84477-d377-4b76-b9dc-f7d9ac0c74e8"),
                            Cpf = "CPF34",
                            DataDeNascimento = new DateTime(2005, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1223),
                            Email = "passageiro34@exemplo.com",
                            Name = "Passageiro 34"
                        },
                        new
                        {
                            Id = new Guid("9296244e-ca65-4241-8cc3-396adebd2104"),
                            Cpf = "CPF35",
                            DataDeNascimento = new DateTime(1975, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1231),
                            Email = "passageiro35@exemplo.com",
                            Name = "Passageiro 35"
                        },
                        new
                        {
                            Id = new Guid("a3e10ce8-2f85-4e77-a166-bd5eb38d07fa"),
                            Cpf = "CPF36",
                            DataDeNascimento = new DateTime(1970, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1243),
                            Email = "passageiro36@exemplo.com",
                            Name = "Passageiro 36"
                        },
                        new
                        {
                            Id = new Guid("57339186-a83e-445a-ade3-2794b62b7f12"),
                            Cpf = "CPF37",
                            DataDeNascimento = new DateTime(1999, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1251),
                            Email = "passageiro37@exemplo.com",
                            Name = "Passageiro 37"
                        },
                        new
                        {
                            Id = new Guid("1c422a23-ed1b-443b-b279-a4d49d7ec976"),
                            Cpf = "CPF38",
                            DataDeNascimento = new DateTime(1987, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1258),
                            Email = "passageiro38@exemplo.com",
                            Name = "Passageiro 38"
                        },
                        new
                        {
                            Id = new Guid("dc49232a-2254-48b5-819b-339c9d64b678"),
                            Cpf = "CPF39",
                            DataDeNascimento = new DateTime(2003, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1265),
                            Email = "passageiro39@exemplo.com",
                            Name = "Passageiro 39"
                        },
                        new
                        {
                            Id = new Guid("31937700-8a33-4b10-a74e-4b7e292dd7af"),
                            Cpf = "CPF40",
                            DataDeNascimento = new DateTime(2000, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1275),
                            Email = "passageiro40@exemplo.com",
                            Name = "Passageiro 40"
                        },
                        new
                        {
                            Id = new Guid("f2d878ae-7e31-4baf-a7aa-0bf51812da5a"),
                            Cpf = "CPF41",
                            DataDeNascimento = new DateTime(1966, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1411),
                            Email = "passageiro41@exemplo.com",
                            Name = "Passageiro 41"
                        },
                        new
                        {
                            Id = new Guid("59f7e68d-5b83-436f-8e33-b9a190b3fee8"),
                            Cpf = "CPF42",
                            DataDeNascimento = new DateTime(1998, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1420),
                            Email = "passageiro42@exemplo.com",
                            Name = "Passageiro 42"
                        },
                        new
                        {
                            Id = new Guid("3be78a25-1414-4cc2-8c11-2def71523696"),
                            Cpf = "CPF43",
                            DataDeNascimento = new DateTime(1995, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1427),
                            Email = "passageiro43@exemplo.com",
                            Name = "Passageiro 43"
                        },
                        new
                        {
                            Id = new Guid("81a0cd6f-01a0-405f-8536-f242bb84d7b3"),
                            Cpf = "CPF44",
                            DataDeNascimento = new DateTime(2003, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1440),
                            Email = "passageiro44@exemplo.com",
                            Name = "Passageiro 44"
                        },
                        new
                        {
                            Id = new Guid("d6689bf3-22dd-4437-8bcb-ea97b897e6db"),
                            Cpf = "CPF45",
                            DataDeNascimento = new DateTime(1976, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1448),
                            Email = "passageiro45@exemplo.com",
                            Name = "Passageiro 45"
                        },
                        new
                        {
                            Id = new Guid("945c7b16-894a-4124-8cf6-42393b5ababb"),
                            Cpf = "CPF46",
                            DataDeNascimento = new DateTime(2002, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1457),
                            Email = "passageiro46@exemplo.com",
                            Name = "Passageiro 46"
                        },
                        new
                        {
                            Id = new Guid("164cacb6-ff14-4f62-862d-eefd6998dded"),
                            Cpf = "CPF47",
                            DataDeNascimento = new DateTime(1975, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1464),
                            Email = "passageiro47@exemplo.com",
                            Name = "Passageiro 47"
                        },
                        new
                        {
                            Id = new Guid("8ea9ad2f-5268-4f5d-bfbf-f4f4db9975ad"),
                            Cpf = "CPF48",
                            DataDeNascimento = new DateTime(1993, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1476),
                            Email = "passageiro48@exemplo.com",
                            Name = "Passageiro 48"
                        },
                        new
                        {
                            Id = new Guid("905ff45d-6cdf-491b-b4c7-30ffa65878b1"),
                            Cpf = "CPF49",
                            DataDeNascimento = new DateTime(1991, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1483),
                            Email = "passageiro49@exemplo.com",
                            Name = "Passageiro 49"
                        },
                        new
                        {
                            Id = new Guid("846a4459-da67-48c2-a6eb-c0cf164797c5"),
                            Cpf = "CPF50",
                            DataDeNascimento = new DateTime(1990, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1490),
                            Email = "passageiro50@exemplo.com",
                            Name = "Passageiro 50"
                        },
                        new
                        {
                            Id = new Guid("6b422ef2-2cb8-47f2-90d5-e1c3ddd4e503"),
                            Cpf = "CPF51",
                            DataDeNascimento = new DateTime(1971, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1498),
                            Email = "passageiro51@exemplo.com",
                            Name = "Passageiro 51"
                        },
                        new
                        {
                            Id = new Guid("89736338-341d-46bd-9c20-147b09034951"),
                            Cpf = "CPF52",
                            DataDeNascimento = new DateTime(2004, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1510),
                            Email = "passageiro52@exemplo.com",
                            Name = "Passageiro 52"
                        },
                        new
                        {
                            Id = new Guid("875c6338-4c07-4deb-ac81-c930ca163a70"),
                            Cpf = "CPF53",
                            DataDeNascimento = new DateTime(1988, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1517),
                            Email = "passageiro53@exemplo.com",
                            Name = "Passageiro 53"
                        },
                        new
                        {
                            Id = new Guid("b25be2a1-d18f-43bb-bf61-e4104b61032c"),
                            Cpf = "CPF54",
                            DataDeNascimento = new DateTime(1980, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1525),
                            Email = "passageiro54@exemplo.com",
                            Name = "Passageiro 54"
                        },
                        new
                        {
                            Id = new Guid("3b4a3863-e526-43d0-aa02-337e8701dcc2"),
                            Cpf = "CPF55",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1531),
                            Email = "passageiro55@exemplo.com",
                            Name = "Passageiro 55"
                        },
                        new
                        {
                            Id = new Guid("c8d07e5f-34a0-4970-97ac-073ae9c37e6b"),
                            Cpf = "CPF56",
                            DataDeNascimento = new DateTime(2004, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1542),
                            Email = "passageiro56@exemplo.com",
                            Name = "Passageiro 56"
                        },
                        new
                        {
                            Id = new Guid("a3724f92-53ec-4eb4-9cda-64b975493d06"),
                            Cpf = "CPF57",
                            DataDeNascimento = new DateTime(1988, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1549),
                            Email = "passageiro57@exemplo.com",
                            Name = "Passageiro 57"
                        },
                        new
                        {
                            Id = new Guid("0119f6d9-21b8-4f56-b89e-90ce6941e8ae"),
                            Cpf = "CPF58",
                            DataDeNascimento = new DateTime(1968, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1557),
                            Email = "passageiro58@exemplo.com",
                            Name = "Passageiro 58"
                        },
                        new
                        {
                            Id = new Guid("3463713c-9471-4015-8a1f-92efdff0c7db"),
                            Cpf = "CPF59",
                            DataDeNascimento = new DateTime(2004, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1564),
                            Email = "passageiro59@exemplo.com",
                            Name = "Passageiro 59"
                        },
                        new
                        {
                            Id = new Guid("c728cd76-0fbd-4ea9-8e26-7f3d8fbcafcf"),
                            Cpf = "CPF60",
                            DataDeNascimento = new DateTime(1967, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1694),
                            Email = "passageiro60@exemplo.com",
                            Name = "Passageiro 60"
                        },
                        new
                        {
                            Id = new Guid("0fc83a78-f134-4bfa-841b-a6c88bfb6441"),
                            Cpf = "CPF61",
                            DataDeNascimento = new DateTime(1966, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1701),
                            Email = "passageiro61@exemplo.com",
                            Name = "Passageiro 61"
                        },
                        new
                        {
                            Id = new Guid("c1c6cb5e-1d0e-4d6a-91b6-e4764ea2fa66"),
                            Cpf = "CPF62",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1709),
                            Email = "passageiro62@exemplo.com",
                            Name = "Passageiro 62"
                        },
                        new
                        {
                            Id = new Guid("463dace5-a3a4-46b0-a272-71df048040ef"),
                            Cpf = "CPF63",
                            DataDeNascimento = new DateTime(1998, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1716),
                            Email = "passageiro63@exemplo.com",
                            Name = "Passageiro 63"
                        },
                        new
                        {
                            Id = new Guid("5883ee19-a20a-4ec8-b932-6d4b092c6343"),
                            Cpf = "CPF64",
                            DataDeNascimento = new DateTime(1976, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1727),
                            Email = "passageiro64@exemplo.com",
                            Name = "Passageiro 64"
                        },
                        new
                        {
                            Id = new Guid("4788aadb-db25-4259-8591-c22497977b00"),
                            Cpf = "CPF65",
                            DataDeNascimento = new DateTime(1975, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1735),
                            Email = "passageiro65@exemplo.com",
                            Name = "Passageiro 65"
                        },
                        new
                        {
                            Id = new Guid("89da3421-146a-4eb3-a759-ef7fc29a3218"),
                            Cpf = "CPF66",
                            DataDeNascimento = new DateTime(2003, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1743),
                            Email = "passageiro66@exemplo.com",
                            Name = "Passageiro 66"
                        },
                        new
                        {
                            Id = new Guid("8451c509-88f6-4191-9010-7d8d771ac57d"),
                            Cpf = "CPF67",
                            DataDeNascimento = new DateTime(1993, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1750),
                            Email = "passageiro67@exemplo.com",
                            Name = "Passageiro 67"
                        },
                        new
                        {
                            Id = new Guid("7319e484-1594-4a3a-b454-c1ea505aa639"),
                            Cpf = "CPF68",
                            DataDeNascimento = new DateTime(1997, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1759),
                            Email = "passageiro68@exemplo.com",
                            Name = "Passageiro 68"
                        },
                        new
                        {
                            Id = new Guid("85976169-1ea7-4a9a-8575-6959fab80a60"),
                            Cpf = "CPF69",
                            DataDeNascimento = new DateTime(1993, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1767),
                            Email = "passageiro69@exemplo.com",
                            Name = "Passageiro 69"
                        },
                        new
                        {
                            Id = new Guid("606fc6a6-a339-4529-8c21-f6322eb0188d"),
                            Cpf = "CPF70",
                            DataDeNascimento = new DateTime(1995, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1775),
                            Email = "passageiro70@exemplo.com",
                            Name = "Passageiro 70"
                        },
                        new
                        {
                            Id = new Guid("005f8dfc-d4db-47fe-959b-02834d06a386"),
                            Cpf = "CPF71",
                            DataDeNascimento = new DateTime(1977, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1783),
                            Email = "passageiro71@exemplo.com",
                            Name = "Passageiro 71"
                        },
                        new
                        {
                            Id = new Guid("3fd0aaa3-a7e2-4b10-b9de-0ba22a041562"),
                            Cpf = "CPF72",
                            DataDeNascimento = new DateTime(1988, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1795),
                            Email = "passageiro72@exemplo.com",
                            Name = "Passageiro 72"
                        },
                        new
                        {
                            Id = new Guid("92e2c7c0-c306-4bc5-9d0a-c0bc6ea3b45e"),
                            Cpf = "CPF73",
                            DataDeNascimento = new DateTime(1977, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1802),
                            Email = "passageiro73@exemplo.com",
                            Name = "Passageiro 73"
                        },
                        new
                        {
                            Id = new Guid("ed5e390f-2b38-4567-8511-fc72141e77cf"),
                            Cpf = "CPF74",
                            DataDeNascimento = new DateTime(2003, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1810),
                            Email = "passageiro74@exemplo.com",
                            Name = "Passageiro 74"
                        },
                        new
                        {
                            Id = new Guid("8daaaeb6-d72a-4a78-b2b6-07c67a10b16d"),
                            Cpf = "CPF75",
                            DataDeNascimento = new DateTime(1973, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1818),
                            Email = "passageiro75@exemplo.com",
                            Name = "Passageiro 75"
                        },
                        new
                        {
                            Id = new Guid("fcd4b8da-9c26-4cee-b179-a5f654da75d7"),
                            Cpf = "CPF76",
                            DataDeNascimento = new DateTime(1993, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1829),
                            Email = "passageiro76@exemplo.com",
                            Name = "Passageiro 76"
                        },
                        new
                        {
                            Id = new Guid("50ff4b0a-5cea-4f61-8156-57c36b600934"),
                            Cpf = "CPF77",
                            DataDeNascimento = new DateTime(1966, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1836),
                            Email = "passageiro77@exemplo.com",
                            Name = "Passageiro 77"
                        },
                        new
                        {
                            Id = new Guid("7df03d65-cfcd-4b86-b9b1-a8b802addab4"),
                            Cpf = "CPF78",
                            DataDeNascimento = new DateTime(1967, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1844),
                            Email = "passageiro78@exemplo.com",
                            Name = "Passageiro 78"
                        },
                        new
                        {
                            Id = new Guid("6334941a-5319-45cc-8139-820875216f84"),
                            Cpf = "CPF79",
                            DataDeNascimento = new DateTime(1997, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1851),
                            Email = "passageiro79@exemplo.com",
                            Name = "Passageiro 79"
                        },
                        new
                        {
                            Id = new Guid("530416a0-9b30-4208-8cde-aec72b63073f"),
                            Cpf = "CPF80",
                            DataDeNascimento = new DateTime(1988, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1861),
                            Email = "passageiro80@exemplo.com",
                            Name = "Passageiro 80"
                        },
                        new
                        {
                            Id = new Guid("421a3419-db80-4ef2-a1f5-b9fdc3fee139"),
                            Cpf = "CPF81",
                            DataDeNascimento = new DateTime(1967, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1869),
                            Email = "passageiro81@exemplo.com",
                            Name = "Passageiro 81"
                        },
                        new
                        {
                            Id = new Guid("8e5f0d3f-4b1f-4cc2-beba-d2c4c3fe47eb"),
                            Cpf = "CPF82",
                            DataDeNascimento = new DateTime(1978, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1877),
                            Email = "passageiro82@exemplo.com",
                            Name = "Passageiro 82"
                        },
                        new
                        {
                            Id = new Guid("eb3b11fe-0702-4415-82da-5d177a2e6009"),
                            Cpf = "CPF83",
                            DataDeNascimento = new DateTime(1982, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1884),
                            Email = "passageiro83@exemplo.com",
                            Name = "Passageiro 83"
                        },
                        new
                        {
                            Id = new Guid("b45e46be-c2f3-4eb5-ba37-1b9be28e9439"),
                            Cpf = "CPF84",
                            DataDeNascimento = new DateTime(2001, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1895),
                            Email = "passageiro84@exemplo.com",
                            Name = "Passageiro 84"
                        },
                        new
                        {
                            Id = new Guid("6e53a264-c36d-4191-b9bf-7b0fd18257de"),
                            Cpf = "CPF85",
                            DataDeNascimento = new DateTime(1966, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1902),
                            Email = "passageiro85@exemplo.com",
                            Name = "Passageiro 85"
                        },
                        new
                        {
                            Id = new Guid("c200cd36-d66e-421e-bc4f-809ecd372407"),
                            Cpf = "CPF86",
                            DataDeNascimento = new DateTime(1970, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1909),
                            Email = "passageiro86@exemplo.com",
                            Name = "Passageiro 86"
                        },
                        new
                        {
                            Id = new Guid("2c6c8565-addf-4b5e-8ee9-32f414dede98"),
                            Cpf = "CPF87",
                            DataDeNascimento = new DateTime(1996, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1916),
                            Email = "passageiro87@exemplo.com",
                            Name = "Passageiro 87"
                        },
                        new
                        {
                            Id = new Guid("c027435b-bef4-4394-b32a-d42bae16ac06"),
                            Cpf = "CPF88",
                            DataDeNascimento = new DateTime(2000, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1927),
                            Email = "passageiro88@exemplo.com",
                            Name = "Passageiro 88"
                        },
                        new
                        {
                            Id = new Guid("84f53e85-971f-455b-87fc-5ba54df5729b"),
                            Cpf = "CPF89",
                            DataDeNascimento = new DateTime(1997, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1935),
                            Email = "passageiro89@exemplo.com",
                            Name = "Passageiro 89"
                        },
                        new
                        {
                            Id = new Guid("fbd30c8f-8ed4-4fbd-b137-7c0a5a24a0d0"),
                            Cpf = "CPF90",
                            DataDeNascimento = new DateTime(1999, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1943),
                            Email = "passageiro90@exemplo.com",
                            Name = "Passageiro 90"
                        },
                        new
                        {
                            Id = new Guid("2924f44f-86ca-4e06-a346-c68517a379ee"),
                            Cpf = "CPF91",
                            DataDeNascimento = new DateTime(1972, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1950),
                            Email = "passageiro91@exemplo.com",
                            Name = "Passageiro 91"
                        },
                        new
                        {
                            Id = new Guid("ee4c6d7a-3db4-47c7-b56d-c32986e44f01"),
                            Cpf = "CPF92",
                            DataDeNascimento = new DateTime(2004, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1961),
                            Email = "passageiro92@exemplo.com",
                            Name = "Passageiro 92"
                        },
                        new
                        {
                            Id = new Guid("9117588b-6221-45be-a28a-c6534069d878"),
                            Cpf = "CPF93",
                            DataDeNascimento = new DateTime(1994, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1968),
                            Email = "passageiro93@exemplo.com",
                            Name = "Passageiro 93"
                        },
                        new
                        {
                            Id = new Guid("c2c572f3-be11-4ff9-9fb1-795f5b95ce81"),
                            Cpf = "CPF94",
                            DataDeNascimento = new DateTime(2006, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1976),
                            Email = "passageiro94@exemplo.com",
                            Name = "Passageiro 94"
                        },
                        new
                        {
                            Id = new Guid("c7ca67f7-64c9-4297-a259-0bd10360624c"),
                            Cpf = "CPF95",
                            DataDeNascimento = new DateTime(1969, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1983),
                            Email = "passageiro95@exemplo.com",
                            Name = "Passageiro 95"
                        },
                        new
                        {
                            Id = new Guid("de09e1fc-3e27-470c-847c-60796ddc2c26"),
                            Cpf = "CPF96",
                            DataDeNascimento = new DateTime(1998, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(1996),
                            Email = "passageiro96@exemplo.com",
                            Name = "Passageiro 96"
                        },
                        new
                        {
                            Id = new Guid("0795d654-3526-498a-9ddc-e0c93cf5f4fc"),
                            Cpf = "CPF97",
                            DataDeNascimento = new DateTime(1984, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(2072),
                            Email = "passageiro97@exemplo.com",
                            Name = "Passageiro 97"
                        },
                        new
                        {
                            Id = new Guid("2be73e48-b0f1-4746-b188-40a80c7964bf"),
                            Cpf = "CPF98",
                            DataDeNascimento = new DateTime(1967, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(2081),
                            Email = "passageiro98@exemplo.com",
                            Name = "Passageiro 98"
                        },
                        new
                        {
                            Id = new Guid("b4a384fb-6d8a-4e54-9274-e735ceea7b0a"),
                            Cpf = "CPF99",
                            DataDeNascimento = new DateTime(1998, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(2088),
                            Email = "passageiro99@exemplo.com",
                            Name = "Passageiro 99"
                        },
                        new
                        {
                            Id = new Guid("1ae4d259-3264-49de-8967-50721a74500c"),
                            Cpf = "CPF100",
                            DataDeNascimento = new DateTime(1979, 1, 28, 18, 21, 8, 964, DateTimeKind.Local).AddTicks(2100),
                            Email = "passageiro100@exemplo.com",
                            Name = "Passageiro 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
