// <auto-generated />
using System;
using BackEndAeroQA.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndAeroQA.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextVoo))]
    [Migration("20240128213006_AppDbContextVooCMigration")]
    partial class AppDbContextVooCMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Voo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraDeChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraDePartida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeDosAssentos")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("ValorDoAssento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Voos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63a61cb4-691d-45dd-be9b-b3bcda5244cf"),
                            DataHoraDeChegada = new DateTime(2024, 2, 18, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(8979),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(8960),
                            Destino = "Destino 1",
                            Origem = "Origem 1",
                            QuantidadeDosAssentos = 26,
                            Tipo = 0,
                            ValorDoAssento = 4251.0
                        },
                        new
                        {
                            Id = new Guid("e4c91533-7c7e-41fd-b980-844767737373"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(8987),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(8986),
                            Destino = "Destino 2",
                            Origem = "Origem 2",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 1372.0
                        },
                        new
                        {
                            Id = new Guid("e300f141-3dae-4a47-a359-cd2f21703a71"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(8992),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(8991),
                            Destino = "Destino 3",
                            Origem = "Origem 3",
                            QuantidadeDosAssentos = 49,
                            Tipo = 0,
                            ValorDoAssento = 4479.0
                        },
                        new
                        {
                            Id = new Guid("52a9b051-84ac-4071-9d0f-3971468e465d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9001),
                            DataHoraDePartida = new DateTime(2024, 2, 16, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9000),
                            Destino = "Destino 4",
                            Origem = "Origem 4",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 2459.0
                        },
                        new
                        {
                            Id = new Guid("0edcadf5-288f-4a08-8f7c-ae1ed9f27bf6"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9006),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9005),
                            Destino = "Destino 5",
                            Origem = "Origem 5",
                            QuantidadeDosAssentos = 34,
                            Tipo = 0,
                            ValorDoAssento = 4795.0
                        },
                        new
                        {
                            Id = new Guid("e43608d5-bff3-4812-8990-e4d4bd5690e8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9010),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9010),
                            Destino = "Destino 6",
                            Origem = "Origem 6",
                            QuantidadeDosAssentos = 47,
                            Tipo = 0,
                            ValorDoAssento = 3116.0
                        },
                        new
                        {
                            Id = new Guid("c62f35ff-286c-43f3-9478-e696acbf962d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9014),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9014),
                            Destino = "Destino 7",
                            Origem = "Origem 7",
                            QuantidadeDosAssentos = 36,
                            Tipo = 0,
                            ValorDoAssento = 4978.0
                        },
                        new
                        {
                            Id = new Guid("427f471e-5f33-4130-8417-81c0abe308d9"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9022),
                            DataHoraDePartida = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9021),
                            Destino = "Destino 8",
                            Origem = "Origem 8",
                            QuantidadeDosAssentos = 28,
                            Tipo = 0,
                            ValorDoAssento = 1595.0
                        },
                        new
                        {
                            Id = new Guid("49f1b38f-8701-43c4-87fa-ffbe70a31a03"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9026),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9026),
                            Destino = "Destino 9",
                            Origem = "Origem 9",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 4191.0
                        },
                        new
                        {
                            Id = new Guid("3700c599-d287-436b-a7e7-a999b061cc99"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9033),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9033),
                            Destino = "Destino 10",
                            Origem = "Origem 10",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 500.0
                        },
                        new
                        {
                            Id = new Guid("65009930-734e-47af-a3c3-8fff647673a8"),
                            DataHoraDeChegada = new DateTime(2024, 1, 30, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9038),
                            DataHoraDePartida = new DateTime(2024, 1, 31, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9037),
                            Destino = "Destino 11",
                            Origem = "Origem 11",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 3477.0
                        },
                        new
                        {
                            Id = new Guid("7ebbb31c-01ea-44b2-9a87-9b09604c7872"),
                            DataHoraDeChegada = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9045),
                            DataHoraDePartida = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9044),
                            Destino = "Destino 12",
                            Origem = "Origem 12",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 2458.0
                        },
                        new
                        {
                            Id = new Guid("342124e9-af85-4f3c-a52f-af7457f24111"),
                            DataHoraDeChegada = new DateTime(2024, 2, 9, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9050),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9049),
                            Destino = "Destino 13",
                            Origem = "Origem 13",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 2213.0
                        },
                        new
                        {
                            Id = new Guid("e6c1095d-3079-4f4f-9658-0ba2d255040e"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9054),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9054),
                            Destino = "Destino 14",
                            Origem = "Origem 14",
                            QuantidadeDosAssentos = 29,
                            Tipo = 0,
                            ValorDoAssento = 1668.0
                        },
                        new
                        {
                            Id = new Guid("e490d8a0-a55f-4268-9bcc-49694ccdbb98"),
                            DataHoraDeChegada = new DateTime(2024, 2, 16, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9059),
                            DataHoraDePartida = new DateTime(2024, 2, 24, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9058),
                            Destino = "Destino 15",
                            Origem = "Origem 15",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 4346.0
                        },
                        new
                        {
                            Id = new Guid("bb6f8831-1275-4c4d-a0fd-24f75e56bf0d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9066),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9065),
                            Destino = "Destino 16",
                            Origem = "Origem 16",
                            QuantidadeDosAssentos = 28,
                            Tipo = 0,
                            ValorDoAssento = 624.0
                        },
                        new
                        {
                            Id = new Guid("93ce639f-03ef-49cf-a9cd-6263e28806d1"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9070),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9070),
                            Destino = "Destino 17",
                            Origem = "Origem 17",
                            QuantidadeDosAssentos = 26,
                            Tipo = 0,
                            ValorDoAssento = 909.0
                        },
                        new
                        {
                            Id = new Guid("5f7f8fd4-7c66-4109-87f8-3552f7356ce4"),
                            DataHoraDeChegada = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9075),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9074),
                            Destino = "Destino 18",
                            Origem = "Origem 18",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 995.0
                        },
                        new
                        {
                            Id = new Guid("70a22f78-cbd7-4a6e-9366-1c203f303abe"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9080),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9079),
                            Destino = "Destino 19",
                            Origem = "Origem 19",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 525.0
                        },
                        new
                        {
                            Id = new Guid("2b2effb7-e200-4fcd-a71f-1013660776f0"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9087),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9086),
                            Destino = "Destino 20",
                            Origem = "Origem 20",
                            QuantidadeDosAssentos = 36,
                            Tipo = 0,
                            ValorDoAssento = 2779.0
                        },
                        new
                        {
                            Id = new Guid("0de9dcfe-59a6-410c-9146-c84cf33f1ab5"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9092),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9091),
                            Destino = "Destino 21",
                            Origem = "Origem 21",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 1999.0
                        },
                        new
                        {
                            Id = new Guid("438cbbeb-7c17-47c0-a7ed-b9ac1de37082"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9127),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9126),
                            Destino = "Destino 22",
                            Origem = "Origem 22",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 3287.0
                        },
                        new
                        {
                            Id = new Guid("5d7b5253-0c26-4a2d-aee6-2f43d1c59582"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9132),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9132),
                            Destino = "Destino 23",
                            Origem = "Origem 23",
                            QuantidadeDosAssentos = 42,
                            Tipo = 0,
                            ValorDoAssento = 2283.0
                        },
                        new
                        {
                            Id = new Guid("7d6c9c19-691b-4cca-9cc2-8c0f713d4ea5"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9139),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9138),
                            Destino = "Destino 24",
                            Origem = "Origem 24",
                            QuantidadeDosAssentos = 47,
                            Tipo = 0,
                            ValorDoAssento = 3660.0
                        },
                        new
                        {
                            Id = new Guid("a0545f95-e4d7-4436-b165-962c3dd93313"),
                            DataHoraDeChegada = new DateTime(2024, 2, 6, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9143),
                            DataHoraDePartida = new DateTime(2024, 2, 25, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9143),
                            Destino = "Destino 25",
                            Origem = "Origem 25",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 3008.0
                        },
                        new
                        {
                            Id = new Guid("26be878e-3a61-43ec-9e9c-67bcda19f467"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9148),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9147),
                            Destino = "Destino 26",
                            Origem = "Origem 26",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 3184.0
                        },
                        new
                        {
                            Id = new Guid("ae1adc51-8c98-45d4-823f-dfb369cd1bad"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9152),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9152),
                            Destino = "Destino 27",
                            Origem = "Origem 27",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 3527.0
                        },
                        new
                        {
                            Id = new Guid("6ef6b602-37c1-4e19-9352-9bf40e4b9089"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9159),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9159),
                            Destino = "Destino 28",
                            Origem = "Origem 28",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 530.0
                        },
                        new
                        {
                            Id = new Guid("35c6a251-2bbd-4090-9706-e72be5db1061"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9164),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9163),
                            Destino = "Destino 29",
                            Origem = "Origem 29",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 4694.0
                        },
                        new
                        {
                            Id = new Guid("99eeda4e-23a7-4bc9-8980-b70c910c7b21"),
                            DataHoraDeChegada = new DateTime(2024, 2, 9, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9168),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9168),
                            Destino = "Destino 30",
                            Origem = "Origem 30",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 2173.0
                        },
                        new
                        {
                            Id = new Guid("0d2859bd-4335-44c6-97fe-6eb62203b8c8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9173),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9172),
                            Destino = "Destino 31",
                            Origem = "Origem 31",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 3115.0
                        },
                        new
                        {
                            Id = new Guid("0e704336-80d7-45e7-ad13-4e1f8cbd97fe"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9180),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9179),
                            Destino = "Destino 32",
                            Origem = "Origem 32",
                            QuantidadeDosAssentos = 31,
                            Tipo = 0,
                            ValorDoAssento = 3750.0
                        },
                        new
                        {
                            Id = new Guid("4db62c44-16ec-4e4c-a14a-fdde4d56a257"),
                            DataHoraDeChegada = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9184),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9183),
                            Destino = "Destino 33",
                            Origem = "Origem 33",
                            QuantidadeDosAssentos = 26,
                            Tipo = 0,
                            ValorDoAssento = 3499.0
                        },
                        new
                        {
                            Id = new Guid("8926bfba-c6e9-4e9b-8053-d90ff66ddb5d"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9188),
                            DataHoraDePartida = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9188),
                            Destino = "Destino 34",
                            Origem = "Origem 34",
                            QuantidadeDosAssentos = 35,
                            Tipo = 0,
                            ValorDoAssento = 2300.0
                        },
                        new
                        {
                            Id = new Guid("391edd94-e7d4-4185-a565-e3e5eaa1c69b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9193),
                            DataHoraDePartida = new DateTime(2024, 1, 31, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9193),
                            Destino = "Destino 35",
                            Origem = "Origem 35",
                            QuantidadeDosAssentos = 48,
                            Tipo = 0,
                            ValorDoAssento = 919.0
                        },
                        new
                        {
                            Id = new Guid("38d37529-fb8a-4506-b38a-0076a69487ec"),
                            DataHoraDeChegada = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9200),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9200),
                            Destino = "Destino 36",
                            Origem = "Origem 36",
                            QuantidadeDosAssentos = 25,
                            Tipo = 0,
                            ValorDoAssento = 2993.0
                        },
                        new
                        {
                            Id = new Guid("a65ebd4c-22e2-4c4a-ade3-4f5b90e3c321"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9205),
                            DataHoraDePartida = new DateTime(2024, 2, 22, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9204),
                            Destino = "Destino 37",
                            Origem = "Origem 37",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 3420.0
                        },
                        new
                        {
                            Id = new Guid("b3a8a9c9-cf0b-492d-910a-6c3ad5be8b5a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9209),
                            DataHoraDePartida = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9208),
                            Destino = "Destino 38",
                            Origem = "Origem 38",
                            QuantidadeDosAssentos = 35,
                            Tipo = 0,
                            ValorDoAssento = 3436.0
                        },
                        new
                        {
                            Id = new Guid("faecb346-1161-415d-a327-da17192eb0ef"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9213),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9213),
                            Destino = "Destino 39",
                            Origem = "Origem 39",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 3757.0
                        },
                        new
                        {
                            Id = new Guid("9b294fb7-1a40-4d89-bcf0-fb130f5665c5"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9221),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9220),
                            Destino = "Destino 40",
                            Origem = "Origem 40",
                            QuantidadeDosAssentos = 38,
                            Tipo = 0,
                            ValorDoAssento = 573.0
                        },
                        new
                        {
                            Id = new Guid("12c2a465-2f7b-44c6-b9f2-582bd128929d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9225),
                            DataHoraDePartida = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9225),
                            Destino = "Destino 41",
                            Origem = "Origem 41",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 3802.0
                        },
                        new
                        {
                            Id = new Guid("45232fcb-dd3a-42a3-8d72-02567e4aed0a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9230),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9229),
                            Destino = "Destino 42",
                            Origem = "Origem 42",
                            QuantidadeDosAssentos = 34,
                            Tipo = 0,
                            ValorDoAssento = 2529.0
                        },
                        new
                        {
                            Id = new Guid("4edbdef7-5f4a-4829-85ac-657671ad3a20"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9235),
                            DataHoraDePartida = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9234),
                            Destino = "Destino 43",
                            Origem = "Origem 43",
                            QuantidadeDosAssentos = 41,
                            Tipo = 0,
                            ValorDoAssento = 4938.0
                        },
                        new
                        {
                            Id = new Guid("c3d1f820-e40f-45e6-ac80-5314cd8d9bc7"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9242),
                            DataHoraDePartida = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9241),
                            Destino = "Destino 44",
                            Origem = "Origem 44",
                            QuantidadeDosAssentos = 26,
                            Tipo = 0,
                            ValorDoAssento = 977.0
                        },
                        new
                        {
                            Id = new Guid("ab1f3d7d-ff18-481b-963b-76957002684b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9247),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9246),
                            Destino = "Destino 45",
                            Origem = "Origem 45",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 1119.0
                        },
                        new
                        {
                            Id = new Guid("51fa9452-78c2-4e1d-88ca-463fa2bd72e3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9251),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9251),
                            Destino = "Destino 46",
                            Origem = "Origem 46",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 3052.0
                        },
                        new
                        {
                            Id = new Guid("4cea38ec-bdd7-48fa-809a-d54ec67a19db"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9256),
                            DataHoraDePartida = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9255),
                            Destino = "Destino 47",
                            Origem = "Origem 47",
                            QuantidadeDosAssentos = 48,
                            Tipo = 0,
                            ValorDoAssento = 885.0
                        },
                        new
                        {
                            Id = new Guid("ecfd45b7-a465-4eab-824a-f79cef2015a4"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9263),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9262),
                            Destino = "Destino 48",
                            Origem = "Origem 48",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 2894.0
                        },
                        new
                        {
                            Id = new Guid("d14fa738-5fdf-4a20-bf86-9ff44d9e109f"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9267),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9266),
                            Destino = "Destino 49",
                            Origem = "Origem 49",
                            QuantidadeDosAssentos = 48,
                            Tipo = 0,
                            ValorDoAssento = 3809.0
                        },
                        new
                        {
                            Id = new Guid("b66a5b74-3db0-40eb-9c08-812c0db0d513"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9272),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9271),
                            Destino = "Destino 50",
                            Origem = "Origem 50",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 4046.0
                        },
                        new
                        {
                            Id = new Guid("bf3d1d85-a962-47a8-bfad-5b69aba67adc"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9276),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9276),
                            Destino = "Destino 51",
                            Origem = "Origem 51",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 4486.0
                        },
                        new
                        {
                            Id = new Guid("f61a63ac-e12f-4c1f-94dc-43e318ed51ad"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9283),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9283),
                            Destino = "Destino 52",
                            Origem = "Origem 52",
                            QuantidadeDosAssentos = 40,
                            Tipo = 0,
                            ValorDoAssento = 4350.0
                        },
                        new
                        {
                            Id = new Guid("550ce2cf-4db3-41f7-a93d-476dff3ba73a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9288),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9287),
                            Destino = "Destino 53",
                            Origem = "Origem 53",
                            QuantidadeDosAssentos = 31,
                            Tipo = 0,
                            ValorDoAssento = 4925.0
                        },
                        new
                        {
                            Id = new Guid("e9bfd351-9aae-4b5c-81b7-ceef21b484e9"),
                            DataHoraDeChegada = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9292),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9292),
                            Destino = "Destino 54",
                            Origem = "Origem 54",
                            QuantidadeDosAssentos = 40,
                            Tipo = 0,
                            ValorDoAssento = 2771.0
                        },
                        new
                        {
                            Id = new Guid("bac3b226-a30c-4ddd-8810-4e8ac35ab3ba"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9297),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9296),
                            Destino = "Destino 55",
                            Origem = "Origem 55",
                            QuantidadeDosAssentos = 48,
                            Tipo = 0,
                            ValorDoAssento = 4724.0
                        },
                        new
                        {
                            Id = new Guid("251eb7bf-d557-4a88-b0b5-0e06f58c6971"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9304),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9303),
                            Destino = "Destino 56",
                            Origem = "Origem 56",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 2709.0
                        },
                        new
                        {
                            Id = new Guid("341bd681-1936-4e48-8186-5031996d9862"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9308),
                            DataHoraDePartida = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9308),
                            Destino = "Destino 57",
                            Origem = "Origem 57",
                            QuantidadeDosAssentos = 38,
                            Tipo = 0,
                            ValorDoAssento = 884.0
                        },
                        new
                        {
                            Id = new Guid("a42bba6f-e762-4e6a-a7a0-3de69dcaa3bf"),
                            DataHoraDeChegada = new DateTime(2024, 1, 31, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9313),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9312),
                            Destino = "Destino 58",
                            Origem = "Origem 58",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 4809.0
                        },
                        new
                        {
                            Id = new Guid("8b4278ac-c0b2-4354-9a03-62f88517856a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 25, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9317),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9316),
                            Destino = "Destino 59",
                            Origem = "Origem 59",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 4729.0
                        },
                        new
                        {
                            Id = new Guid("2fec052f-bce8-419f-9a71-9c9fa5961746"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9324),
                            DataHoraDePartida = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9323),
                            Destino = "Destino 60",
                            Origem = "Origem 60",
                            QuantidadeDosAssentos = 33,
                            Tipo = 0,
                            ValorDoAssento = 1969.0
                        },
                        new
                        {
                            Id = new Guid("be368169-df22-4272-a0c9-a10055b6a120"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9328),
                            DataHoraDePartida = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9328),
                            Destino = "Destino 61",
                            Origem = "Origem 61",
                            QuantidadeDosAssentos = 48,
                            Tipo = 0,
                            ValorDoAssento = 3044.0
                        },
                        new
                        {
                            Id = new Guid("8b0e7b41-395b-4182-a3ce-a855d28a7510"),
                            DataHoraDeChegada = new DateTime(2024, 2, 18, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9333),
                            DataHoraDePartida = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9332),
                            Destino = "Destino 62",
                            Origem = "Origem 62",
                            QuantidadeDosAssentos = 28,
                            Tipo = 0,
                            ValorDoAssento = 3618.0
                        },
                        new
                        {
                            Id = new Guid("1b8fa5aa-9609-4e7d-955b-46075029c648"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9337),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9337),
                            Destino = "Destino 63",
                            Origem = "Origem 63",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 2170.0
                        },
                        new
                        {
                            Id = new Guid("118f4fb6-22a1-4cfb-8e9d-0266035a4838"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9345),
                            DataHoraDePartida = new DateTime(2024, 2, 24, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9344),
                            Destino = "Destino 64",
                            Origem = "Origem 64",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 703.0
                        },
                        new
                        {
                            Id = new Guid("fae5d7e3-01a6-425c-8874-3dd6ae909283"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9349),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9349),
                            Destino = "Destino 65",
                            Origem = "Origem 65",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 3250.0
                        },
                        new
                        {
                            Id = new Guid("dfe32d7a-0870-4be3-a3c7-5e6b60395916"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9354),
                            DataHoraDePartida = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9353),
                            Destino = "Destino 66",
                            Origem = "Origem 66",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 1300.0
                        },
                        new
                        {
                            Id = new Guid("3bd4b036-d397-4cdd-a851-9215697a5d52"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9358),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9358),
                            Destino = "Destino 67",
                            Origem = "Origem 67",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 2331.0
                        },
                        new
                        {
                            Id = new Guid("129eca76-84d2-4245-8dd3-99f52ea852a8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9365),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9365),
                            Destino = "Destino 68",
                            Origem = "Origem 68",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 4454.0
                        },
                        new
                        {
                            Id = new Guid("ccf3b620-8c4a-4812-8e2f-0989b094539b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9369),
                            DataHoraDePartida = new DateTime(2024, 2, 3, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9369),
                            Destino = "Destino 69",
                            Origem = "Origem 69",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 3625.0
                        },
                        new
                        {
                            Id = new Guid("ba218659-62e2-4431-8e7d-fb7291dccc1a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9374),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9373),
                            Destino = "Destino 70",
                            Origem = "Origem 70",
                            QuantidadeDosAssentos = 31,
                            Tipo = 0,
                            ValorDoAssento = 1875.0
                        },
                        new
                        {
                            Id = new Guid("2caff4b6-d493-4275-b4b1-8bb8c97f85a3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9404),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9403),
                            Destino = "Destino 71",
                            Origem = "Origem 71",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 3591.0
                        },
                        new
                        {
                            Id = new Guid("5e25153b-a8f8-43b6-89a1-3a5f3c0aa73a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 10, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9411),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9411),
                            Destino = "Destino 72",
                            Origem = "Origem 72",
                            QuantidadeDosAssentos = 25,
                            Tipo = 0,
                            ValorDoAssento = 2858.0
                        },
                        new
                        {
                            Id = new Guid("cfb9f16e-0fc0-4c29-8f18-2d8ef9b81869"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9416),
                            DataHoraDePartida = new DateTime(2024, 1, 31, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9416),
                            Destino = "Destino 73",
                            Origem = "Origem 73",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 4821.0
                        },
                        new
                        {
                            Id = new Guid("8a03031c-32e9-42de-a569-ed71a7f3fa86"),
                            DataHoraDeChegada = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9421),
                            DataHoraDePartida = new DateTime(2024, 2, 10, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9420),
                            Destino = "Destino 74",
                            Origem = "Origem 74",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 3105.0
                        },
                        new
                        {
                            Id = new Guid("cc6f5ffb-4038-4277-9519-63a24f43141e"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9425),
                            DataHoraDePartida = new DateTime(2024, 1, 30, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9425),
                            Destino = "Destino 75",
                            Origem = "Origem 75",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 2343.0
                        },
                        new
                        {
                            Id = new Guid("7e44d290-ddf1-47e3-b8f4-6731e42331fb"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9433),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9432),
                            Destino = "Destino 76",
                            Origem = "Origem 76",
                            QuantidadeDosAssentos = 35,
                            Tipo = 0,
                            ValorDoAssento = 4844.0
                        },
                        new
                        {
                            Id = new Guid("613a4973-12e3-411b-8fba-14537eadbd9a"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9437),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9437),
                            Destino = "Destino 77",
                            Origem = "Origem 77",
                            QuantidadeDosAssentos = 49,
                            Tipo = 0,
                            ValorDoAssento = 1961.0
                        },
                        new
                        {
                            Id = new Guid("adeec236-7db7-4602-919b-450e4caf4898"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9442),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9441),
                            Destino = "Destino 78",
                            Origem = "Origem 78",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 3113.0
                        },
                        new
                        {
                            Id = new Guid("60c19ef2-b3d4-4de1-956e-9af474a0c7c3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9446),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9446),
                            Destino = "Destino 79",
                            Origem = "Origem 79",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 1471.0
                        },
                        new
                        {
                            Id = new Guid("15260632-f0f1-4321-93d5-bb80b3af0ee5"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9453),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9453),
                            Destino = "Destino 80",
                            Origem = "Origem 80",
                            QuantidadeDosAssentos = 31,
                            Tipo = 0,
                            ValorDoAssento = 2810.0
                        },
                        new
                        {
                            Id = new Guid("b3a619ef-e8d2-4e33-9269-e598cfbafe8a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9458),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9457),
                            Destino = "Destino 81",
                            Origem = "Origem 81",
                            QuantidadeDosAssentos = 28,
                            Tipo = 0,
                            ValorDoAssento = 1854.0
                        },
                        new
                        {
                            Id = new Guid("ad9ffc39-16ad-4f90-bdff-c091c7e546db"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9462),
                            DataHoraDePartida = new DateTime(2024, 2, 16, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9462),
                            Destino = "Destino 82",
                            Origem = "Origem 82",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 1304.0
                        },
                        new
                        {
                            Id = new Guid("51c1a0a7-6623-4fd2-b42a-69abd5ca2112"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9467),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9467),
                            Destino = "Destino 83",
                            Origem = "Origem 83",
                            QuantidadeDosAssentos = 47,
                            Tipo = 0,
                            ValorDoAssento = 4900.0
                        },
                        new
                        {
                            Id = new Guid("ab595cef-cf78-4d2a-a432-cd2bda64a72e"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9475),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9474),
                            Destino = "Destino 84",
                            Origem = "Origem 84",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 4962.0
                        },
                        new
                        {
                            Id = new Guid("47ba617d-bdc1-4233-926c-1175de0eb471"),
                            DataHoraDeChegada = new DateTime(2024, 1, 31, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9480),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9479),
                            Destino = "Destino 85",
                            Origem = "Origem 85",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 4545.0
                        },
                        new
                        {
                            Id = new Guid("df6c490a-c7ce-495a-b4ab-3087d6b1ad0f"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9484),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9484),
                            Destino = "Destino 86",
                            Origem = "Origem 86",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 3214.0
                        },
                        new
                        {
                            Id = new Guid("c9740cc7-a967-4481-9609-28da71de2afd"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9489),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9488),
                            Destino = "Destino 87",
                            Origem = "Origem 87",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 4804.0
                        },
                        new
                        {
                            Id = new Guid("1a8cd9e4-d7c0-4a01-b85b-2222de87df5b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9496),
                            DataHoraDePartida = new DateTime(2024, 2, 3, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9496),
                            Destino = "Destino 88",
                            Origem = "Origem 88",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 2565.0
                        },
                        new
                        {
                            Id = new Guid("ee47bce9-2b3d-4ba8-a2c5-0550c21ebfc2"),
                            DataHoraDeChegada = new DateTime(2024, 2, 9, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9501),
                            DataHoraDePartida = new DateTime(2024, 2, 16, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9501),
                            Destino = "Destino 89",
                            Origem = "Origem 89",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 2845.0
                        },
                        new
                        {
                            Id = new Guid("8db65486-1b11-4038-82ab-32f4433fa14f"),
                            DataHoraDeChegada = new DateTime(2024, 2, 5, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9506),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9505),
                            Destino = "Destino 90",
                            Origem = "Origem 90",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 3433.0
                        },
                        new
                        {
                            Id = new Guid("b7182dfa-cd44-4c7f-acc5-216431fd6484"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9510),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9510),
                            Destino = "Destino 91",
                            Origem = "Origem 91",
                            QuantidadeDosAssentos = 41,
                            Tipo = 0,
                            ValorDoAssento = 2186.0
                        },
                        new
                        {
                            Id = new Guid("9b49b340-879a-4e5c-afb7-25115417cdc6"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9518),
                            DataHoraDePartida = new DateTime(2024, 2, 16, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9517),
                            Destino = "Destino 92",
                            Origem = "Origem 92",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 1288.0
                        },
                        new
                        {
                            Id = new Guid("0c394b77-9efa-43a5-8712-501a871d1967"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9522),
                            DataHoraDePartida = new DateTime(2024, 2, 10, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9522),
                            Destino = "Destino 93",
                            Origem = "Origem 93",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 1444.0
                        },
                        new
                        {
                            Id = new Guid("ab1f80e0-b84d-4d07-9f84-8872bb76ad9e"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9527),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9526),
                            Destino = "Destino 94",
                            Origem = "Origem 94",
                            QuantidadeDosAssentos = 26,
                            Tipo = 0,
                            ValorDoAssento = 3046.0
                        },
                        new
                        {
                            Id = new Guid("b9f781d7-85a8-45bf-8a85-1e4c59e869b6"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9531),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9531),
                            Destino = "Destino 95",
                            Origem = "Origem 95",
                            QuantidadeDosAssentos = 26,
                            Tipo = 0,
                            ValorDoAssento = 4017.0
                        },
                        new
                        {
                            Id = new Guid("cfc1408c-ccb0-4678-84bd-795dd3d9ee14"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9539),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9538),
                            Destino = "Destino 96",
                            Origem = "Origem 96",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 1087.0
                        },
                        new
                        {
                            Id = new Guid("c7def3dd-6ec4-434f-bc4d-79215fe77907"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9543),
                            DataHoraDePartida = new DateTime(2024, 2, 21, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9542),
                            Destino = "Destino 97",
                            Origem = "Origem 97",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 1059.0
                        },
                        new
                        {
                            Id = new Guid("dcbbe05d-fdb8-4481-b220-3979622813f6"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9547),
                            DataHoraDePartida = new DateTime(2024, 2, 26, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9547),
                            Destino = "Destino 98",
                            Origem = "Origem 98",
                            QuantidadeDosAssentos = 48,
                            Tipo = 0,
                            ValorDoAssento = 2879.0
                        },
                        new
                        {
                            Id = new Guid("cc8602c4-08ac-46c8-96cc-47e96a280b18"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9553),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9552),
                            Destino = "Destino 99",
                            Origem = "Origem 99",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 4441.0
                        },
                        new
                        {
                            Id = new Guid("551886c4-50ae-405b-ad93-4e1765912e83"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9560),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 30, 6, 490, DateTimeKind.Local).AddTicks(9560),
                            Destino = "Destino 100",
                            Origem = "Origem 100",
                            QuantidadeDosAssentos = 37,
                            Tipo = 0,
                            ValorDoAssento = 3290.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
