// <auto-generated />
using System;
using BackEndAeroQA.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndAeroQA.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextVoo))]
    [Migration("20240128212409_AppDbContextVooMigration")]
    partial class AppDbContextVooMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Voo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraDeChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraDePartida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeDosAssentos")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("ValorDoAssento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Voos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c103dbf-4014-44a5-a479-df0a7e3ae34c"),
                            DataHoraDeChegada = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7974),
                            DataHoraDePartida = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7953),
                            Destino = "Destino 1",
                            Origem = "Origem 1",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 3103.0
                        },
                        new
                        {
                            Id = new Guid("82cb1be0-16a5-4050-8f76-0d48c6014dd1"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7982),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7981),
                            Destino = "Destino 2",
                            Origem = "Origem 2",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 2305.0
                        },
                        new
                        {
                            Id = new Guid("fe80169c-0188-4e99-b179-26aa5fb198fb"),
                            DataHoraDeChegada = new DateTime(2024, 2, 16, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7986),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7986),
                            Destino = "Destino 3",
                            Origem = "Origem 3",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 2411.0
                        },
                        new
                        {
                            Id = new Guid("55900ddc-cda6-49fc-8413-643df01e5c35"),
                            DataHoraDeChegada = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7995),
                            DataHoraDePartida = new DateTime(2024, 2, 10, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7994),
                            Destino = "Destino 4",
                            Origem = "Origem 4",
                            QuantidadeDosAssentos = 29,
                            Tipo = 0,
                            ValorDoAssento = 4580.0
                        },
                        new
                        {
                            Id = new Guid("4370d7d4-e415-4aeb-90ae-231d47485e88"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7999),
                            DataHoraDePartida = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(7999),
                            Destino = "Destino 5",
                            Origem = "Origem 5",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 4373.0
                        },
                        new
                        {
                            Id = new Guid("68c70e1e-c78d-499b-8666-020dcbb01ebe"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8003),
                            DataHoraDePartida = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8003),
                            Destino = "Destino 6",
                            Origem = "Origem 6",
                            QuantidadeDosAssentos = 37,
                            Tipo = 0,
                            ValorDoAssento = 1503.0
                        },
                        new
                        {
                            Id = new Guid("002b40f6-d5a8-480a-a5ed-085590c62c9f"),
                            DataHoraDeChegada = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8008),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8007),
                            Destino = "Destino 7",
                            Origem = "Origem 7",
                            QuantidadeDosAssentos = 33,
                            Tipo = 0,
                            ValorDoAssento = 2654.0
                        },
                        new
                        {
                            Id = new Guid("38d1aa1c-8cdb-499f-8512-884c17a3567c"),
                            DataHoraDeChegada = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8015),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8014),
                            Destino = "Destino 8",
                            Origem = "Origem 8",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 4566.0
                        },
                        new
                        {
                            Id = new Guid("76272b88-2810-4974-9be9-e87fddbf1cce"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8019),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8018),
                            Destino = "Destino 9",
                            Origem = "Origem 9",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 2656.0
                        },
                        new
                        {
                            Id = new Guid("009329cc-78bf-4236-84d7-badeded7130c"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8027),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8027),
                            Destino = "Destino 10",
                            Origem = "Origem 10",
                            QuantidadeDosAssentos = 42,
                            Tipo = 0,
                            ValorDoAssento = 1860.0
                        },
                        new
                        {
                            Id = new Guid("8c5c316b-857e-4845-a6f2-9da7cd51276c"),
                            DataHoraDeChegada = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8032),
                            DataHoraDePartida = new DateTime(2024, 1, 29, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8031),
                            Destino = "Destino 11",
                            Origem = "Origem 11",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 918.0
                        },
                        new
                        {
                            Id = new Guid("3028e1e2-b9c5-4549-bd38-716afe3a81af"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8039),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8038),
                            Destino = "Destino 12",
                            Origem = "Origem 12",
                            QuantidadeDosAssentos = 28,
                            Tipo = 0,
                            ValorDoAssento = 3668.0
                        },
                        new
                        {
                            Id = new Guid("ba3c2329-a76a-4049-bb2c-7dfaebb4de81"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8043),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8042),
                            Destino = "Destino 13",
                            Origem = "Origem 13",
                            QuantidadeDosAssentos = 40,
                            Tipo = 0,
                            ValorDoAssento = 1928.0
                        },
                        new
                        {
                            Id = new Guid("b8c2d062-5c86-430b-ad0e-77d6b6d88ef6"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8047),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8046),
                            Destino = "Destino 14",
                            Origem = "Origem 14",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 1271.0
                        },
                        new
                        {
                            Id = new Guid("4e447074-174d-4142-a87e-1b931d98ed14"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8051),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8051),
                            Destino = "Destino 15",
                            Origem = "Origem 15",
                            QuantidadeDosAssentos = 29,
                            Tipo = 0,
                            ValorDoAssento = 2005.0
                        },
                        new
                        {
                            Id = new Guid("69a6095b-ac2b-4b77-af7d-d81b5ae1de3f"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8094),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8093),
                            Destino = "Destino 16",
                            Origem = "Origem 16",
                            QuantidadeDosAssentos = 25,
                            Tipo = 0,
                            ValorDoAssento = 4172.0
                        },
                        new
                        {
                            Id = new Guid("be7edd56-2678-4086-a97b-b8cf0aaf893c"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8099),
                            DataHoraDePartida = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8098),
                            Destino = "Destino 17",
                            Origem = "Origem 17",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 4846.0
                        },
                        new
                        {
                            Id = new Guid("8911519e-04e8-4715-8999-675bb94771b3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8103),
                            DataHoraDePartida = new DateTime(2024, 2, 16, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8102),
                            Destino = "Destino 18",
                            Origem = "Origem 18",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 3089.0
                        },
                        new
                        {
                            Id = new Guid("40e53762-c470-4b4a-9d0b-056532ae603d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8107),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8106),
                            Destino = "Destino 19",
                            Origem = "Origem 19",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 4445.0
                        },
                        new
                        {
                            Id = new Guid("172d31b4-3713-4fe9-ab9a-ac4826d9b636"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8114),
                            DataHoraDePartida = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8113),
                            Destino = "Destino 20",
                            Origem = "Origem 20",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 2722.0
                        },
                        new
                        {
                            Id = new Guid("4686cc97-1380-44fd-b487-86bf02f2569c"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8118),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8117),
                            Destino = "Destino 21",
                            Origem = "Origem 21",
                            QuantidadeDosAssentos = 31,
                            Tipo = 0,
                            ValorDoAssento = 2008.0
                        },
                        new
                        {
                            Id = new Guid("4b706f6b-1c28-462d-b3e2-2c830f672778"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8122),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8122),
                            Destino = "Destino 22",
                            Origem = "Origem 22",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 543.0
                        },
                        new
                        {
                            Id = new Guid("b381fe78-2e3f-42d1-b45f-02e2dbf6d8d8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8126),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8126),
                            Destino = "Destino 23",
                            Origem = "Origem 23",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 2172.0
                        },
                        new
                        {
                            Id = new Guid("a18a9bc4-1156-4dad-b79b-7ea5f24f4df6"),
                            DataHoraDeChegada = new DateTime(2024, 1, 31, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8133),
                            DataHoraDePartida = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8133),
                            Destino = "Destino 24",
                            Origem = "Origem 24",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 1017.0
                        },
                        new
                        {
                            Id = new Guid("c0cf4f7b-3850-4f94-9dec-415e2d5f9848"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8137),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8137),
                            Destino = "Destino 25",
                            Origem = "Origem 25",
                            QuantidadeDosAssentos = 34,
                            Tipo = 0,
                            ValorDoAssento = 2634.0
                        },
                        new
                        {
                            Id = new Guid("8dd2d61d-63c4-4ec0-83f2-92b0a9dbdb0b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8141),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8141),
                            Destino = "Destino 26",
                            Origem = "Origem 26",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 503.0
                        },
                        new
                        {
                            Id = new Guid("a454d8ed-f387-4728-9bf3-9666b917237e"),
                            DataHoraDeChegada = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8146),
                            DataHoraDePartida = new DateTime(2024, 2, 26, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8145),
                            Destino = "Destino 27",
                            Origem = "Origem 27",
                            QuantidadeDosAssentos = 47,
                            Tipo = 0,
                            ValorDoAssento = 2367.0
                        },
                        new
                        {
                            Id = new Guid("46e124cc-7b3c-4444-aae8-e66dac1fbfba"),
                            DataHoraDeChegada = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8153),
                            DataHoraDePartida = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8152),
                            Destino = "Destino 28",
                            Origem = "Origem 28",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 4153.0
                        },
                        new
                        {
                            Id = new Guid("acee92c3-233b-48fa-927b-df6404b8f750"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8157),
                            DataHoraDePartida = new DateTime(2024, 2, 21, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8156),
                            Destino = "Destino 29",
                            Origem = "Origem 29",
                            QuantidadeDosAssentos = 37,
                            Tipo = 0,
                            ValorDoAssento = 1485.0
                        },
                        new
                        {
                            Id = new Guid("62ce3269-2623-4bbd-9d30-c37b597ae2f8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8161),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8160),
                            Destino = "Destino 30",
                            Origem = "Origem 30",
                            QuantidadeDosAssentos = 38,
                            Tipo = 0,
                            ValorDoAssento = 1658.0
                        },
                        new
                        {
                            Id = new Guid("cfddcb24-9b11-4095-9ff0-383ccddde2ad"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8165),
                            DataHoraDePartida = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8164),
                            Destino = "Destino 31",
                            Origem = "Origem 31",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 2461.0
                        },
                        new
                        {
                            Id = new Guid("43fc09bc-6d01-4d00-b5a7-f3e58da10629"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8172),
                            DataHoraDePartida = new DateTime(2024, 2, 21, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8171),
                            Destino = "Destino 32",
                            Origem = "Origem 32",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 691.0
                        },
                        new
                        {
                            Id = new Guid("d276c8fe-5916-46c0-ae6b-a7f89f0630a3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8176),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8175),
                            Destino = "Destino 33",
                            Origem = "Origem 33",
                            QuantidadeDosAssentos = 42,
                            Tipo = 0,
                            ValorDoAssento = 3166.0
                        },
                        new
                        {
                            Id = new Guid("ab13d557-3b2a-4cbc-bd7a-e47a30a3b54a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8180),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8179),
                            Destino = "Destino 34",
                            Origem = "Origem 34",
                            QuantidadeDosAssentos = 38,
                            Tipo = 0,
                            ValorDoAssento = 2048.0
                        },
                        new
                        {
                            Id = new Guid("c06e953f-50f0-4d3f-9f4a-3e83292c1922"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8184),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8184),
                            Destino = "Destino 35",
                            Origem = "Origem 35",
                            QuantidadeDosAssentos = 35,
                            Tipo = 0,
                            ValorDoAssento = 4546.0
                        },
                        new
                        {
                            Id = new Guid("331f593a-51cf-4313-a8e4-1d86b88669f1"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8191),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8191),
                            Destino = "Destino 36",
                            Origem = "Origem 36",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 3416.0
                        },
                        new
                        {
                            Id = new Guid("b38c88df-8625-47dc-aaac-9c324d0f907a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8196),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8195),
                            Destino = "Destino 37",
                            Origem = "Origem 37",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 1992.0
                        },
                        new
                        {
                            Id = new Guid("2bbe29cf-a288-4fac-9175-d8d52073cc15"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8200),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8199),
                            Destino = "Destino 38",
                            Origem = "Origem 38",
                            QuantidadeDosAssentos = 33,
                            Tipo = 0,
                            ValorDoAssento = 3378.0
                        },
                        new
                        {
                            Id = new Guid("798fa6c1-4fc4-4c0f-9a1c-fe87dfcbce1d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8204),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8203),
                            Destino = "Destino 39",
                            Origem = "Origem 39",
                            QuantidadeDosAssentos = 37,
                            Tipo = 0,
                            ValorDoAssento = 1521.0
                        },
                        new
                        {
                            Id = new Guid("8ca0ddd5-6280-45cd-9623-f3f76d58e891"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8211),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8211),
                            Destino = "Destino 40",
                            Origem = "Origem 40",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 4364.0
                        },
                        new
                        {
                            Id = new Guid("4a149484-9c56-4969-8795-8244fc2af9ac"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8216),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8215),
                            Destino = "Destino 41",
                            Origem = "Origem 41",
                            QuantidadeDosAssentos = 36,
                            Tipo = 0,
                            ValorDoAssento = 2073.0
                        },
                        new
                        {
                            Id = new Guid("476f736e-03d0-4815-9363-8182542e96a3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8220),
                            DataHoraDePartida = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8219),
                            Destino = "Destino 42",
                            Origem = "Origem 42",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 1571.0
                        },
                        new
                        {
                            Id = new Guid("71d8074e-1152-40e4-8fa8-ba39e1da35c6"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8224),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8224),
                            Destino = "Destino 43",
                            Origem = "Origem 43",
                            QuantidadeDosAssentos = 42,
                            Tipo = 0,
                            ValorDoAssento = 2191.0
                        },
                        new
                        {
                            Id = new Guid("ccb93018-3fa7-4e1a-9f3f-d02a32d099d8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8231),
                            DataHoraDePartida = new DateTime(2024, 1, 29, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8231),
                            Destino = "Destino 44",
                            Origem = "Origem 44",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 4536.0
                        },
                        new
                        {
                            Id = new Guid("8fb5b56b-5d75-4736-a0ba-c92b8b983ef1"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8235),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8235),
                            Destino = "Destino 45",
                            Origem = "Origem 45",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 1086.0
                        },
                        new
                        {
                            Id = new Guid("8ad1d695-8cb6-4c97-86ac-68fdf822261f"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8239),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8239),
                            Destino = "Destino 46",
                            Origem = "Origem 46",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 3863.0
                        },
                        new
                        {
                            Id = new Guid("66ffb846-24f6-4568-a898-52aee504e3a0"),
                            DataHoraDeChegada = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8244),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8243),
                            Destino = "Destino 47",
                            Origem = "Origem 47",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 2964.0
                        },
                        new
                        {
                            Id = new Guid("a6960b1f-9bfa-4636-9491-83f5b21fca16"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8250),
                            DataHoraDePartida = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8250),
                            Destino = "Destino 48",
                            Origem = "Origem 48",
                            QuantidadeDosAssentos = 47,
                            Tipo = 0,
                            ValorDoAssento = 4239.0
                        },
                        new
                        {
                            Id = new Guid("acab75be-3f95-42ee-ac8b-5cee67eac529"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8255),
                            DataHoraDePartida = new DateTime(2024, 1, 31, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8254),
                            Destino = "Destino 49",
                            Origem = "Origem 49",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 3252.0
                        },
                        new
                        {
                            Id = new Guid("d4a77f69-9f07-4487-8d32-4d7c06f034cd"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8259),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8258),
                            Destino = "Destino 50",
                            Origem = "Origem 50",
                            QuantidadeDosAssentos = 41,
                            Tipo = 0,
                            ValorDoAssento = 1088.0
                        },
                        new
                        {
                            Id = new Guid("7659c3d7-5adc-43ff-9627-a90f8f8264e2"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8263),
                            DataHoraDePartida = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8263),
                            Destino = "Destino 51",
                            Origem = "Origem 51",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 3950.0
                        },
                        new
                        {
                            Id = new Guid("76ee94ca-7538-45a0-91bd-f98eb6d1a1df"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8270),
                            DataHoraDePartida = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8269),
                            Destino = "Destino 52",
                            Origem = "Origem 52",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 2105.0
                        },
                        new
                        {
                            Id = new Guid("412f91da-4b7b-44c3-a758-31590c1b7a0b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8274),
                            DataHoraDePartida = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8273),
                            Destino = "Destino 53",
                            Origem = "Origem 53",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 1113.0
                        },
                        new
                        {
                            Id = new Guid("eaf79fe1-8113-4b4f-8563-1c07e034d231"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8278),
                            DataHoraDePartida = new DateTime(2024, 2, 3, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8278),
                            Destino = "Destino 54",
                            Origem = "Origem 54",
                            QuantidadeDosAssentos = 33,
                            Tipo = 0,
                            ValorDoAssento = 2947.0
                        },
                        new
                        {
                            Id = new Guid("0f32ad46-0110-410f-b06e-8e9c167a30b9"),
                            DataHoraDeChegada = new DateTime(2024, 1, 29, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8282),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8282),
                            Destino = "Destino 55",
                            Origem = "Origem 55",
                            QuantidadeDosAssentos = 34,
                            Tipo = 0,
                            ValorDoAssento = 3522.0
                        },
                        new
                        {
                            Id = new Guid("b5f6b564-0161-413b-b94d-f12975cf1891"),
                            DataHoraDeChegada = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8290),
                            DataHoraDePartida = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8289),
                            Destino = "Destino 56",
                            Origem = "Origem 56",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 4846.0
                        },
                        new
                        {
                            Id = new Guid("f6120895-18bd-4db5-a992-2e71a52d26ae"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8294),
                            DataHoraDePartida = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8293),
                            Destino = "Destino 57",
                            Origem = "Origem 57",
                            QuantidadeDosAssentos = 41,
                            Tipo = 0,
                            ValorDoAssento = 4433.0
                        },
                        new
                        {
                            Id = new Guid("8c2db102-8bf9-4675-b486-c8e04244b257"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8298),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8297),
                            Destino = "Destino 58",
                            Origem = "Origem 58",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 4343.0
                        },
                        new
                        {
                            Id = new Guid("29a0259e-efa3-4deb-a8cb-7aacb045bca9"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8302),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8301),
                            Destino = "Destino 59",
                            Origem = "Origem 59",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 1056.0
                        },
                        new
                        {
                            Id = new Guid("5c9dd07f-93d6-41e8-b2cd-0c69fb7b0265"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8309),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8308),
                            Destino = "Destino 60",
                            Origem = "Origem 60",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 2667.0
                        },
                        new
                        {
                            Id = new Guid("73ba9b54-6683-4664-b7f5-b672e5428c3a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8313),
                            DataHoraDePartida = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8313),
                            Destino = "Destino 61",
                            Origem = "Origem 61",
                            QuantidadeDosAssentos = 29,
                            Tipo = 0,
                            ValorDoAssento = 2938.0
                        },
                        new
                        {
                            Id = new Guid("8b23f91d-f4d1-4d57-9588-31c40dbea69d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8317),
                            DataHoraDePartida = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8317),
                            Destino = "Destino 62",
                            Origem = "Origem 62",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 2114.0
                        },
                        new
                        {
                            Id = new Guid("d6465714-3924-4247-bb6c-f823b80f4958"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8321),
                            DataHoraDePartida = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8321),
                            Destino = "Destino 63",
                            Origem = "Origem 63",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 3012.0
                        },
                        new
                        {
                            Id = new Guid("053127f5-329c-42b6-b812-ceb2e6931f09"),
                            DataHoraDeChegada = new DateTime(2024, 2, 16, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8329),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8328),
                            Destino = "Destino 64",
                            Origem = "Origem 64",
                            QuantidadeDosAssentos = 44,
                            Tipo = 0,
                            ValorDoAssento = 4475.0
                        },
                        new
                        {
                            Id = new Guid("9679ddfc-b6be-4a48-bb37-82d5a23a77e3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8362),
                            DataHoraDePartida = new DateTime(2024, 2, 8, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8361),
                            Destino = "Destino 65",
                            Origem = "Origem 65",
                            QuantidadeDosAssentos = 46,
                            Tipo = 0,
                            ValorDoAssento = 3132.0
                        },
                        new
                        {
                            Id = new Guid("7d5ec02e-5a50-47e0-8ad4-40de32ddf297"),
                            DataHoraDeChegada = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8366),
                            DataHoraDePartida = new DateTime(2024, 2, 10, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8366),
                            Destino = "Destino 66",
                            Origem = "Origem 66",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 1476.0
                        },
                        new
                        {
                            Id = new Guid("f0d228dc-6685-42d8-8a67-a28be924539c"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8370),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8370),
                            Destino = "Destino 67",
                            Origem = "Origem 67",
                            QuantidadeDosAssentos = 41,
                            Tipo = 0,
                            ValorDoAssento = 4947.0
                        },
                        new
                        {
                            Id = new Guid("6e67747a-1d66-4336-9d76-3000b7293b5d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 13, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8378),
                            DataHoraDePartida = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8377),
                            Destino = "Destino 68",
                            Origem = "Origem 68",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 840.0
                        },
                        new
                        {
                            Id = new Guid("bb0e0dfc-62d8-4d66-8740-cafa7717bfe5"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8382),
                            DataHoraDePartida = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8381),
                            Destino = "Destino 69",
                            Origem = "Origem 69",
                            QuantidadeDosAssentos = 30,
                            Tipo = 0,
                            ValorDoAssento = 4101.0
                        },
                        new
                        {
                            Id = new Guid("767c4f26-d504-42a7-a9d9-c7356685daa5"),
                            DataHoraDeChegada = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8386),
                            DataHoraDePartida = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8385),
                            Destino = "Destino 70",
                            Origem = "Origem 70",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 2987.0
                        },
                        new
                        {
                            Id = new Guid("9cb02df6-ccc7-40e7-945a-10b64ebe9b9e"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8390),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8390),
                            Destino = "Destino 71",
                            Origem = "Origem 71",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 520.0
                        },
                        new
                        {
                            Id = new Guid("82067006-0dee-4686-ae27-448efb948099"),
                            DataHoraDeChegada = new DateTime(2024, 2, 7, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8397),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8397),
                            Destino = "Destino 72",
                            Origem = "Origem 72",
                            QuantidadeDosAssentos = 36,
                            Tipo = 0,
                            ValorDoAssento = 4453.0
                        },
                        new
                        {
                            Id = new Guid("9fa4467c-9430-4460-aebe-e24bb6abfc68"),
                            DataHoraDeChegada = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8401),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8401),
                            Destino = "Destino 73",
                            Origem = "Origem 73",
                            QuantidadeDosAssentos = 49,
                            Tipo = 0,
                            ValorDoAssento = 2947.0
                        },
                        new
                        {
                            Id = new Guid("62992bad-a256-437e-8494-db43a4d3a0d6"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8406),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8405),
                            Destino = "Destino 74",
                            Origem = "Origem 74",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 1090.0
                        },
                        new
                        {
                            Id = new Guid("2c4b8d00-bd9c-4b78-bd60-031b5de78fae"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8410),
                            DataHoraDePartida = new DateTime(2024, 2, 11, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8409),
                            Destino = "Destino 75",
                            Origem = "Origem 75",
                            QuantidadeDosAssentos = 31,
                            Tipo = 0,
                            ValorDoAssento = 2138.0
                        },
                        new
                        {
                            Id = new Guid("193d7ceb-86ac-464d-b3b0-466001f7df42"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8416),
                            DataHoraDePartida = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8416),
                            Destino = "Destino 76",
                            Origem = "Origem 76",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 2728.0
                        },
                        new
                        {
                            Id = new Guid("f8b6da2e-45a0-4aff-a08f-62a81d4b76fd"),
                            DataHoraDeChegada = new DateTime(2024, 2, 21, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8421),
                            DataHoraDePartida = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8420),
                            Destino = "Destino 77",
                            Origem = "Origem 77",
                            QuantidadeDosAssentos = 35,
                            Tipo = 0,
                            ValorDoAssento = 1803.0
                        },
                        new
                        {
                            Id = new Guid("d54e58d2-837b-4c31-9d2b-2a923e81173a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 7, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8425),
                            DataHoraDePartida = new DateTime(2024, 2, 21, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8424),
                            Destino = "Destino 78",
                            Origem = "Origem 78",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 1006.0
                        },
                        new
                        {
                            Id = new Guid("050e6d75-aace-48ca-90a1-45a0d60179a2"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8429),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8428),
                            Destino = "Destino 79",
                            Origem = "Origem 79",
                            QuantidadeDosAssentos = 38,
                            Tipo = 0,
                            ValorDoAssento = 1002.0
                        },
                        new
                        {
                            Id = new Guid("1b2f9fa8-8940-4876-b1de-1b5461711501"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8436),
                            DataHoraDePartida = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8436),
                            Destino = "Destino 80",
                            Origem = "Origem 80",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 3946.0
                        },
                        new
                        {
                            Id = new Guid("0eb6a14a-e47e-4024-bb28-34f6dca27a6d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8441),
                            DataHoraDePartida = new DateTime(2024, 2, 7, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8440),
                            Destino = "Destino 81",
                            Origem = "Origem 81",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 4499.0
                        },
                        new
                        {
                            Id = new Guid("2a34cd90-f09a-4629-bdc2-b85f08323d2f"),
                            DataHoraDeChegada = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8445),
                            DataHoraDePartida = new DateTime(2024, 2, 3, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8444),
                            Destino = "Destino 82",
                            Origem = "Origem 82",
                            QuantidadeDosAssentos = 45,
                            Tipo = 0,
                            ValorDoAssento = 2875.0
                        },
                        new
                        {
                            Id = new Guid("862e9ead-b00b-407b-9b15-c9db193cd9e3"),
                            DataHoraDeChegada = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8449),
                            DataHoraDePartida = new DateTime(2024, 1, 29, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8448),
                            Destino = "Destino 83",
                            Origem = "Origem 83",
                            QuantidadeDosAssentos = 27,
                            Tipo = 0,
                            ValorDoAssento = 3852.0
                        },
                        new
                        {
                            Id = new Guid("49f3892d-72ee-44d3-bf2f-903c80c47fcf"),
                            DataHoraDeChegada = new DateTime(2024, 2, 8, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8455),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8455),
                            Destino = "Destino 84",
                            Origem = "Origem 84",
                            QuantidadeDosAssentos = 41,
                            Tipo = 0,
                            ValorDoAssento = 1510.0
                        },
                        new
                        {
                            Id = new Guid("732e4177-6f05-459d-8860-82e2e8bdc366"),
                            DataHoraDeChegada = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8460),
                            DataHoraDePartida = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8459),
                            Destino = "Destino 85",
                            Origem = "Origem 85",
                            QuantidadeDosAssentos = 43,
                            Tipo = 0,
                            ValorDoAssento = 1306.0
                        },
                        new
                        {
                            Id = new Guid("0a01e5ac-d496-49b3-bfec-f62f91c017bf"),
                            DataHoraDeChegada = new DateTime(2024, 2, 1, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8464),
                            DataHoraDePartida = new DateTime(2024, 1, 31, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8463),
                            Destino = "Destino 86",
                            Origem = "Origem 86",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 1761.0
                        },
                        new
                        {
                            Id = new Guid("eff5296c-55d4-4385-8ad3-6051ccd7a94b"),
                            DataHoraDeChegada = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8468),
                            DataHoraDePartida = new DateTime(2024, 2, 19, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8467),
                            Destino = "Destino 87",
                            Origem = "Origem 87",
                            QuantidadeDosAssentos = 42,
                            Tipo = 0,
                            ValorDoAssento = 3013.0
                        },
                        new
                        {
                            Id = new Guid("ebcbf9ca-4961-4502-9282-ef038fa7007a"),
                            DataHoraDeChegada = new DateTime(2024, 2, 20, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8475),
                            DataHoraDePartida = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8474),
                            Destino = "Destino 88",
                            Origem = "Origem 88",
                            QuantidadeDosAssentos = 33,
                            Tipo = 0,
                            ValorDoAssento = 4884.0
                        },
                        new
                        {
                            Id = new Guid("e20c62e3-1a1f-40cf-949a-ffb05b1cf731"),
                            DataHoraDeChegada = new DateTime(2024, 2, 12, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8479),
                            DataHoraDePartida = new DateTime(2024, 2, 15, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8479),
                            Destino = "Destino 89",
                            Origem = "Origem 89",
                            QuantidadeDosAssentos = 29,
                            Tipo = 0,
                            ValorDoAssento = 1180.0
                        },
                        new
                        {
                            Id = new Guid("35247efe-bc4f-453d-a0a3-2ab8d4a2e1b8"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8484),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8483),
                            Destino = "Destino 90",
                            Origem = "Origem 90",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 1700.0
                        },
                        new
                        {
                            Id = new Guid("4656ab10-7de6-4f95-befa-bccf279f4a36"),
                            DataHoraDeChegada = new DateTime(2024, 2, 9, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8488),
                            DataHoraDePartida = new DateTime(2024, 2, 4, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8487),
                            Destino = "Destino 91",
                            Origem = "Origem 91",
                            QuantidadeDosAssentos = 23,
                            Tipo = 0,
                            ValorDoAssento = 4331.0
                        },
                        new
                        {
                            Id = new Guid("8c627783-ac87-42e6-a6de-294ff024fd7f"),
                            DataHoraDeChegada = new DateTime(2024, 2, 22, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8495),
                            DataHoraDePartida = new DateTime(2024, 2, 18, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8494),
                            Destino = "Destino 92",
                            Origem = "Origem 92",
                            QuantidadeDosAssentos = 42,
                            Tipo = 0,
                            ValorDoAssento = 3695.0
                        },
                        new
                        {
                            Id = new Guid("b1452650-e5d8-455f-a0bf-e96952b87581"),
                            DataHoraDeChegada = new DateTime(2024, 2, 24, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8499),
                            DataHoraDePartida = new DateTime(2024, 2, 6, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8499),
                            Destino = "Destino 93",
                            Origem = "Origem 93",
                            QuantidadeDosAssentos = 22,
                            Tipo = 0,
                            ValorDoAssento = 1709.0
                        },
                        new
                        {
                            Id = new Guid("94f828cd-5b23-47c0-9445-2666b564e548"),
                            DataHoraDeChegada = new DateTime(2024, 2, 25, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8503),
                            DataHoraDePartida = new DateTime(2024, 2, 16, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8503),
                            Destino = "Destino 94",
                            Origem = "Origem 94",
                            QuantidadeDosAssentos = 25,
                            Tipo = 0,
                            ValorDoAssento = 4887.0
                        },
                        new
                        {
                            Id = new Guid("dfb8ff14-b864-4373-a217-92b644d80f5c"),
                            DataHoraDeChegada = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8507),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8507),
                            Destino = "Destino 95",
                            Origem = "Origem 95",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 547.0
                        },
                        new
                        {
                            Id = new Guid("06b86653-a3d4-4c38-8dd8-de4545113ea1"),
                            DataHoraDeChegada = new DateTime(2024, 2, 19, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8514),
                            DataHoraDePartida = new DateTime(2024, 2, 23, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8514),
                            Destino = "Destino 96",
                            Origem = "Origem 96",
                            QuantidadeDosAssentos = 32,
                            Tipo = 0,
                            ValorDoAssento = 3743.0
                        },
                        new
                        {
                            Id = new Guid("5bf69656-ae1b-450b-8476-682982a95c76"),
                            DataHoraDeChegada = new DateTime(2024, 1, 30, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8518),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8518),
                            Destino = "Destino 97",
                            Origem = "Origem 97",
                            QuantidadeDosAssentos = 24,
                            Tipo = 0,
                            ValorDoAssento = 3027.0
                        },
                        new
                        {
                            Id = new Guid("a3376918-4121-40cf-9dcd-f67e3947af9d"),
                            DataHoraDeChegada = new DateTime(2024, 2, 3, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8523),
                            DataHoraDePartida = new DateTime(2024, 2, 2, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8522),
                            Destino = "Destino 98",
                            Origem = "Origem 98",
                            QuantidadeDosAssentos = 38,
                            Tipo = 0,
                            ValorDoAssento = 1686.0
                        },
                        new
                        {
                            Id = new Guid("d11d2a89-4157-4de9-b044-282d500f2a90"),
                            DataHoraDeChegada = new DateTime(2024, 2, 26, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8527),
                            DataHoraDePartida = new DateTime(2024, 2, 14, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8526),
                            Destino = "Destino 99",
                            Origem = "Origem 99",
                            QuantidadeDosAssentos = 39,
                            Tipo = 0,
                            ValorDoAssento = 3155.0
                        },
                        new
                        {
                            Id = new Guid("44684391-164f-4b9e-8975-d4e0c7d804ec"),
                            DataHoraDeChegada = new DateTime(2024, 2, 17, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8534),
                            DataHoraDePartida = new DateTime(2024, 2, 5, 18, 24, 8, 247, DateTimeKind.Local).AddTicks(8534),
                            Destino = "Destino 100",
                            Origem = "Origem 100",
                            QuantidadeDosAssentos = 33,
                            Tipo = 0,
                            ValorDoAssento = 868.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
