// <auto-generated />
using System;
using BackEndAeroQA.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndAeroQA.Infrastructure.Migrations.DbContextAeroportoMigrations
{
    [DbContext(typeof(DbContextAeroporto))]
    partial class DbContextAeroportoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEndAeroQA.Domain.Entity.Aeroporto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aeroportos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d886b1e9-51fd-476b-8dae-71a524729e55"),
                            Cidade = "Rio de Janeiro",
                            Codigo = 1000,
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("59ae45a3-ab8a-4da6-8843-e1815c2b089b"),
                            Cidade = "São Paulo",
                            Codigo = 1001,
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("6300b85d-66ae-4ee4-8ae0-231ae025903d"),
                            Cidade = "Belo Horizonte",
                            Codigo = 1002,
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("418029f8-4757-45df-ac43-edd9f655a81c"),
                            Cidade = "Brasília",
                            Codigo = 1003,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("afc80cc6-af3f-4847-ad2a-23a71881504f"),
                            Cidade = "Salvador",
                            Codigo = 1004,
                            UF = "BA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
